groups:
  - name: example
    rules:
      - record: foo_request_rate
        expr: rate(foo_total{job="example5"}[1m])

      - record: foo_error_rate
        expr: rate(foo_error_total{job="example5"}[1m])

      - record: foo_error_percent
        expr: 100*foo_error_total{job="example5"}/foo_total{job="example5"}

      - record: foo_duration_mean_seconds
        expr: foo_duration_seconds_sum{job="example5"}/foo_duration_seconds_count{job="example5"}
